language: ruby
rvm:
  - 2.1
  
before_install:
  - gem install bundler
  #- sudo service postgresql stop
  - ls /usr/lib/postgresql/9.1/bin
  - sudo apt-get install postgresql

  
script: bundle exec rspec
